name: Build

on:
  - push
  - pull_request

jobs:
  vite:
    name: Vite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
        name: Install pnpm
        with:
          run_install: true
          cache: true

      - run: pnpm run build
